language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
# command to install dependencies
before install:
  - pip install pypandoc
  - pandoc --from=markdown --to=rst --output=README.rst README.md

install:
  - pip install -e .
# command to run tests
script:
  - bash scripts/test.sh

notifications:
  email: false
